CREATE DATABASE spare;

USE spare;

CREATE TABLE product (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product VARCHAR(45) NOT NULL
);

DESCRIBE product;

CREATE TABLE brand (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  brand VARCHAR(45) NOT NULL
);

DESCRIBE brand;

CREATE TABLE model (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  model VARCHAR(45) NOT NULL,
  product_id INT(20) NOT NULL,
  brand_id INT(20) NOT NULL,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (brand_id) REFERENCES brand(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE model;

CREATE TABLE lot (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lot VARCHAR(45) NOT NULL,
  model_id INT(20) NOT NULL,
  cant INT(20) NOT NULL,
  FOREIGN KEY (model_id) REFERENCES model(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE lot;

CREATE TABLE entry (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lot_id INT(20) NOT NULL,
  serial VARCHAR(45) NOT NULL UNIQUE,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lot_id) REFERENCES lot(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE entry;

CREATE TABLE output (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lot_id INT(20) NOT NULL,
  serial VARCHAR(45) NOT NULL UNIQUE,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lot_id) REFERENCES lot(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE output;

CREATE TABLE inventory (
  id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entry_id INT(20) NOT NULL,
  output_id INT(20) NOT NULL,
  stock INT(50) NOT NULL,
  FOREIGN KEY (entry_id) REFERENCES entry(id) ON DELETE CASCADE ON UPDATE CASCADE,  
  FOREIGN KEY (output_id) REFERENCES output(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DESCRIBE inventory;
